language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.3
before_install:
  - gem install bundler -v 1.10.6
  - bin/setup
script: "bundle exec rspec spec"
gemfile:
  - gemfiles/rails_4.2.4.gemfile
  - gemfiles/rails_3.2.22.gemfile
addons:
  postgresql: "9.4" # json_build_object was introduced in 9.4
